### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kkh975** [kkh975/2210_image-picker#3]
- [x] 생성시 대표 픽셀 조사하기
- [x] 이미지 사이즈 리사이즈
- [x] 확대경 그리기 (canvas shape 이용)
- [x] 확대경 움직이기
    - [x] 확대경 가장자리 문제가 있으니, 실제 사이즈는 그것보다 작게 그리기
 - [x] 화대경의 가운데 position의 rgb 얻어오기 
 - [x] 움직일때마다

**Comment by htrucci** [comment]
https://ibb.co/sJdwt9f
앱에 콜백하는 테스트를 해봤는데요.
역시 치훈맴이 도와주시니 뭔가 조금 되는 느낌이네요 ㅠㅠ

추가로 확인하고 싶은게 몇개 있는데요.
확대경 순서가 꼬이는 케이스가 있는 것 같거든요.
상단 기준으로 확대경 연결 순서를 정하는게 가능할지. 
https://ibb.co/2sQV9Kv

그리고 아래 작업URL을 핸드폰 사파리로 열어서 드래그 했을때 확대경이 드래그되는게 아니고 
윈도우 스크롤이 된다던가 이미지가 선택된다던가 하거든요. 요거 css나 스크립트로 막을 수 있을까요?
http://htrucci.com/colorpicker-2.html

그리고 하나 좀 크리티컬 이슈로 테스트하다가 일부 RGB값은 반영이 안되는걸 확인했는데요.
(조명은 검정색이 없으니까 #000000 일때 버그가 발생하는 그런 부분,,,,)
그래서 불가한 rgb 범위를 좀 찾아서 애초에 추출범위에 없도록 제한을 하거나 표현불가한 색이면 하나를 더 찾는다던지 
그렇게 해야할 것 같은데 일단 업체에 제한범위를 좀 물어보고 생각을 좀 더 해봐야겠습니다 ㅠ

TODO: 웹뷰 width 크기에 맞춰지도록 viewport 처리
